version: "3"

services:
    backend:
        build: .
        volumes:
            - ./app:/app
        networks:
            - nginx_network
            - database1_network
        depends_on:
            - database1

    nginx:
        image: nginx:1.13
        ports:
            - 8000:80
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - backend
        networks:
            - nginx_network

    database1:
        image: postgres:10
        ports:
            - "5432:5432"
        env_file:
            - db/db_env
        networks:
            - database1_network
        volumes:
            - database1_volume:/var/lib/postgresql/data

networks:
    nginx_network:
        driver: bridge
    database1_network:
        driver: bridge

volumes:
    database1_volume: